
# Info
title: Ghostly Swoosh
twitter: "http://twitter.com/ghostlyswooshusf"
github: "http://github.com/joshimbriani"
baseurl: ""
url: "http://ghostlyswoosh.com"

# Collections
collections:
  posts:
    title: Posts
    output: true
    permalink: "/updates/:title"
  areas:
    title: Areas
    output: true
    permalink: "/areas/:name"
  dining:
    title: Dining
    output: true
    permalink: "/dining/:name"
  rides:
    title: Rides and Attractions
    output: true
    permalink: "/rides/:name"
  shopping:
    title: Shopping
    output: true
    permalink: "/shopping/:name"
  shows:
    title: Shows
    output: true
    permalink: "/shows/:name"
  events:
    title: events
    output: true
    permalink: "/events/:name"

# Settings
markdown: kramdown
gems:
excerpt_seperator: "<!--more-->"
destination: "./build"
permalink: "/:title"
exclude:
  - components
  - Gemfile
  - Gemfile.lock
  - ".gitignore"
  - node_modules
  - js/source.js
  - webpack.config.js
  - package.json
  - .jshintrc
  - .sass-cache
  - browser-sync.js
  - npm-debug.log
  - README.MD
sass:
  style: compressed
